os:
  - osx
  - linux
sudo: required
dist: trusty
language: go
go:
- "1.12.x"
env:
  - GO111MODULE=on TF_ACC=true
addons:
  apt:
    packages:
      - gnome-keyring
      - libsecret-tools
      - python-gnomekeyring
script: go test -v ./...

# from github.com/zalando/go-keyring under MIT license
before_script:
  - |
    if [ "${TRAVIS_OS_NAME}" == "linux" ]; then
      dbus-launch /usr/bin/python -c \
        "import gnomekeyring;gnomekeyring.create_sync('login', '');"
    fi
